server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:  
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
    config:
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/