server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujunbao/spring-cloud-config-repo
          default-label: main
          search-paths: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/